const language = {};

language.english = {};
language.english.VOWELS = { A: true, E: true, I: true, O: true, U: true }
// https://en.wikipedia.org/wiki/Swadesh_list#Swadesh_207_list
language.english.SWADESH_LIST = ['I', 'YOU', 'HE', 'WE', 'THEY', 'THIS', 'THAT', 'HERE', 'THERE', 'WHO', 'WHAT', 'WHERE', 'WHEN', 'HOW', 'NOT', 'ALL', 'MANY', 'SOME', 'FEW', 'OTHER', 'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'BIG', 'LONG', 'WIDE', 'THICK', 'HEAVY', 'SMALL', 'SHORT', 'NARROW', 'THIN', 'WOMAN', 'MAN', 'CHILD', 'WIFE', 'HUSBAND', 'MOTHER', 'FATHER', 'ANIMAL', 'FISH', 'BIRD', 'DOG', 'LOUSE', 'SNAKE', 'WORM', 'TREE', 'FOREST', 'STICK', 'FRUIT', 'SEED', 'LEAF', 'ROOT', 'BARK', 'FLOWER', 'GRASS', 'ROPE', 'SKIN', 'MEAT', 'BLOOD', 'BONE', 'FAT', 'EGG', 'HORN', 'TAIL', 'FEATHER', 'HAIR', 'HEAD', 'EAR', 'EYE', 'NOSE', 'MOUTH', 'TOOTH', 'TONGUE', 'FINGERNAIL', 'FOOT', 'LEG', 'KNEE', 'HAND', 'WING', 'BELLY', 'GUTS', 'NECK', 'BACK', 'BREAST', 'HEART', 'LIVER', 'DRINK', 'EAT', 'BITE', 'SUCK', 'SPIT', 'VOMIT', 'BLOW', 'BREATHE', 'LAUGH', 'SEE', 'HEAR', 'KNOW', 'THINK', 'SMELL', 'FEAR', 'SLEEP', 'LIVE', 'DIE', 'KILL', 'FIGHT', 'HUNT', 'HIT', 'CUT', 'SPLIT', 'STAB', 'SCRATCH', 'DIG', 'SWIM', 'FLY', 'WALK', 'COME', 'LIE', 'SIT', 'STAND', 'TURN', 'FALL', 'GIVE', 'HOLD', 'SQUEEZE', 'RUB', 'WASH', 'WIPE', 'PULL', 'PUSH', 'THROW', 'TIE', 'SEW', 'COUNT', 'SAY', 'SING', 'PLAY', 'FLOAT', 'FLOW', 'FREEZE', 'SWELL', 'SUN', 'MOON', 'STAR', 'WATER', 'RAIN', 'RIVER', 'LAKE', 'SEA', 'SALT', 'STONE', 'SAND', 'DUST', 'EARTH', 'CLOUD', 'FOG', 'SKY', 'WIND', 'SNOW', 'ICE', 'SMOKE', 'FIRE', 'ASH', 'BURN', 'ROAD', 'MOUNTAIN', 'RED', 'GREEN', 'YELLOW', 'WHITE', 'BLACK', 'NIGHT', 'DAY', 'YEAR', 'WARM', 'COLD', 'FULL', 'NEW', 'OLD', 'GOOD', 'BAD', 'ROTTEN', 'DIRTY', 'STRAIGHT', 'ROUND', 'SHARP', 'DULL', 'SMOOTH', 'WET', 'DRY', 'CORRECT', 'NEAR', 'FAR', 'RIGHT', 'LEFT', 'AT', 'IN', 'WITH', 'AND', 'IF', 'BECAUSE', 'NAME'];
language.english.NUMERICAL_WORDS = ['ZERO', 'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE', 'TEN', 'ELEVEN', 'TWELVE', 'THIRTEEN', 'FOURTEEN', 'FIFTEEN', 'SIXTEEN', 'SEVENTEEN', 'EIGHTEEN', 'NINETEEN', 'TWENTY', 'THIRTY', 'FORTY', 'FIFTY', 'SIXTY', 'SEVENTY', 'EIGHTY', 'NINETY', 'HUNDRED'];
language.english.NUMERICAL_WORD_VALUES = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 30, 40, 50, 60, 70, 80, 90, 100];
language.english.TEXT_LETTER_FREQUENCIES = { A: .082, B: .015, C: .028, D: .043, E: .13, F: .022, G: .02, H: .061, I: .07, J: .0015, K: .0077, L: .04, M: .024, N: .067, O: .075, P: .019, Q: .00095, R: .06, S: .063, T: .091, U: .028, V: .0098, W: .024, X: .0015, Y: .02, Z: .00074, };
language.english.DICTIONARY_LETTER_FREQUENCIES = { E: .11, S: .087, I: .086, A: .078, R: .073, N: .072, T: .067, O: .061, L: .053, C: .04, D: .038, U: .033, G: .03, P: .028, M: .027, H: .023, B: .02, Y: .016, F: .014, V: .01, K: .0097, W: .0091, Z: .0044, X: .0027, J: .0021, Q: .0019, };

language.scrabble = {};
language.scrabble.LETTER_FREQUENCIES = { E: 12 / 98, A: 9 / 98, I: 9 / 98, O: 8 / 98, N: 6 / 98, R: 6 / 98, T: 6 / 98, L: 4 / 98, S: 4 / 98, U: 4 / 98, D: 4 / 98, G: 3 / 98, B: 2 / 98, C: 2 / 98, M: 2 / 98, P: 2 / 98, F: 2 / 98, H: 2 / 98, V: 2 / 98, W: 2 / 98, Y: 2 / 98, K: 1 / 98, J: 1 / 98, X: 1 / 98, Q: 1 / 98, Z: 1 / 98, };
language.scrabble.LETTER_SCORES = { E: 1, A: 1, I: 1, O: 1, N: 1, R: 1, T: 1, L: 1, S: 1, U: 1, D: 2, G: 2, B: 3, C: 3, M: 3, P: 3, F: 4, H: 4, V: 4, W: 4, Y: 4, K: 5, J: 8, X: 8, Q: 10, Z: 10, };

module.exports = language;